# Generated by Django 4.2.2 on 2023-06-18 16:36

import CosatecaApp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('postalCode', models.CharField(max_length=5)),
                ('imageProfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(max_length=9)),
                ('banned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('SPORTS', 'Sports'), ('MACHINERY', 'Machinery'), ('TOOLS', 'Tools'), ('GARDENING', 'Gardening'), ('VIDEOGAMES', 'Videogames'), ('CONSOLES', 'Consoles'), ('BOOKS', 'Books'), ('PCs', 'Pcs'), ('TABLETS', 'Tablets'), ('MOBILE PHONE', 'Mobile Phone'), ('ART', 'Art')], max_length=12, verbose_name=CosatecaApp.models.Category)),
                ('publicationDate', models.DateField(auto_now_add=True)),
                ('availab', models.BooleanField(default=True)),
                ('userWhoRentProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whoRent', to='CosatecaApp.person')),
                ('userWhoUploadProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoUpload', to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Verificaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'Inprogress'), ('CLOSED', 'Closed')], default='IN PROGRESS', max_length=11)),
                ('userToVerify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('observations', models.CharField(max_length=300)),
                ('reason', models.CharField(choices=[('FRAUDULENT EHAVIOR', 'Fraudulent Behavior'), ('DAMAGE OR LOSS OBJECTS', 'Damage Or Loss Objects'), ('ILLEGAL ACTIVITIES', 'Illegal Activities')], max_length=25, verbose_name=CosatecaApp.models.Reason)),
                ('capture', models.URLField(blank=True, null=True)),
                ('reportedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
                ('reportingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportingUser', to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.product')),
                ('wishList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='MessengerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDate', models.DateTimeField()),
                ('body', models.CharField(max_length=1000)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='CosatecaApp.person')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busyDate', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.product')),
            ],
        ),
    ]
