# Generated by Django 4.2.2 on 2023-06-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verificaction',
            new_name='Verification',
        ),
    ]
