# Generated by Django 4.2.2 on 2023-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0002_rename_verificaction_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imageProfile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
