# Generated by Django 4.2.2 on 2023-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0003_alter_person_imageprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imageProfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
