# Generated by Django 4.2.1 on 2023-05-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imageProfile',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
            ],
        ),
    ]
