# Generated by Django 4.2.2 on 2023-06-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0007_alter_product_category_alter_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='observations',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
