# Generated by Django 4.2.1 on 2023-05-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0007_messengerservice_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Verificaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'Inprogress'), ('CLOSED', 'Closed')], default='IN PROGRESS', max_length=11)),
                ('userToVerify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observations', models.CharField(max_length=300)),
                ('capture', models.URLField(blank=True, null=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.reason')),
                ('reportedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person')),
                ('reportingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportingUser', to='CosatecaApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.product')),
                ('wishList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.wishlist')),
            ],
        ),
    ]
