# Generated by Django 4.2.1 on 2023-05-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0008_reason_wishlist_verificaction_report_productsinlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userWhoUploadProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person'),
        ),
        migrations.AlterField(
            model_name='messengerservice',
            name='sendDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='imageProfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='publicationDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
