# Generated by Django 4.2.2 on 2023-06-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0008_alter_report_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='capture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
