# Generated by Django 4.2.1 on 2023-05-29 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CosatecaApp', '0009_product_userwhouploadproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
        migrations.AddField(
            model_name='person',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='userWhoUploadProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosatecaApp.person'),
        ),
    ]
