# Generated by Django 4.2.2 on 2023-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0009_alter_report_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('IN REVISION', 'In Revision'), ('REJECTED', 'Rejected')], default='IN REVISION', max_length=11),
        ),
    ]
