# Generated by Django 4.2.1 on 2023-05-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0010_remove_person_admin_remove_person_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='usuario',
        ),
        migrations.AddField(
            model_name='person',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
