# Generated by Django 4.2.1 on 2023-05-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0015_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
    ]
