# Generated by Django 4.2.1 on 2023-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0018_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TECNOLOGÍA', 'Tecnología'), ('JARDINERÍA', 'Jardinería')], max_length=11),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
