# Generated by Django 4.2.1 on 2023-05-31 09:56

import CosatecaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0020_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DEPORTES', 'Deportes'), ('MAQUINARIA', 'Maquinaria'), ('HERRAMIENTAS', 'Herramientas')], max_length=12, verbose_name=CosatecaApp.models.Category),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
