# Generated by Django 4.2.1 on 2023-05-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0021_remove_product_barcode_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='null', upload_to='productos'),
        ),
    ]
