# Generated by Django 4.2.2 on 2023-06-17 10:02

import CosatecaApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0024_rename_date_rating_create_date_rating_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('FRAUDULENT EHAVIOR', 'Fraudulent Behavior'), ('DAMAGE OR LOSS OBJECTS', 'Damage Or Loss Objects'), ('ILLEGAL ACTIVITIES', 'Illegal Activities')], max_length=25, verbose_name=CosatecaApp.models.Reason),
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
