# Generated by Django 4.2.2 on 2023-06-17 17:10

import CosatecaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0025_alter_rating_rating_alter_report_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('MACHINERY', 'Machinery'), ('TOOLS', 'Tools'), ('GARDENING', 'Gardening'), ('VIDEOGAMES', 'Videogames'), ('CONSOLES', 'Consoles'), ('BOOKS', 'Books'), ('PCs', 'Pcs'), ('TABLETS', 'Tablets'), ('MOBILE PHONE', 'Mobile Phone')], max_length=12, verbose_name=CosatecaApp.models.Category),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
