# Generated by Django 4.2.2 on 2023-06-17 17:22

import CosatecaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosatecaApp', '0026_alter_product_category_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('MACHINERY', 'Machinery'), ('TOOLS', 'Tools'), ('GARDENING', 'Gardening'), ('VIDEOGAMES', 'Videogames'), ('CONSOLES', 'Consoles'), ('BOOKS', 'Books'), ('PCs', 'Pcs'), ('TABLETS', 'Tablets'), ('MOBILE PHONE', 'Mobile Phone'), ('ART', 'Art')], max_length=12, verbose_name=CosatecaApp.models.Category),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
    ]
